/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ToDoListImport } from './routes/to-do-list'
import { Route as IndexImport } from './routes/index'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as BlogPosts0003HowToGetTheMostOutOfAwsSummitImport } from './routes/blog/posts/0003-how-to-get-the-most-out-of-aws-summit'
import { Route as BlogPosts0002LearningForTheSolutionArchitectCertificateImport } from './routes/blog/posts/0002-learning-for-the-solution-architect-certificate'
import { Route as BlogPosts0001BuildingAwsCloudResumeChallengeImport } from './routes/blog/posts/0001-building-aws-cloud-resume-challenge'

// Create/Update Routes

const ToDoListRoute = ToDoListImport.update({
  path: '/to-do-list',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  path: '/blog/',
  getParentRoute: () => rootRoute,
} as any)

const BlogPosts0003HowToGetTheMostOutOfAwsSummitRoute =
  BlogPosts0003HowToGetTheMostOutOfAwsSummitImport.update({
    path: '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit',
    getParentRoute: () => rootRoute,
  } as any)

const BlogPosts0002LearningForTheSolutionArchitectCertificateRoute =
  BlogPosts0002LearningForTheSolutionArchitectCertificateImport.update({
    path: '/blog/posts/0002-learning-for-the-solution-architect-certificate',
    getParentRoute: () => rootRoute,
  } as any)

const BlogPosts0001BuildingAwsCloudResumeChallengeRoute =
  BlogPosts0001BuildingAwsCloudResumeChallengeImport.update({
    path: '/blog/posts/0001-building-aws-cloud-resume-challenge',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/to-do-list': {
      id: '/to-do-list'
      path: '/to-do-list'
      fullPath: '/to-do-list'
      preLoaderRoute: typeof ToDoListImport
      parentRoute: typeof rootRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof rootRoute
    }
    '/blog/posts/0001-building-aws-cloud-resume-challenge': {
      id: '/blog/posts/0001-building-aws-cloud-resume-challenge'
      path: '/blog/posts/0001-building-aws-cloud-resume-challenge'
      fullPath: '/blog/posts/0001-building-aws-cloud-resume-challenge'
      preLoaderRoute: typeof BlogPosts0001BuildingAwsCloudResumeChallengeImport
      parentRoute: typeof rootRoute
    }
    '/blog/posts/0002-learning-for-the-solution-architect-certificate': {
      id: '/blog/posts/0002-learning-for-the-solution-architect-certificate'
      path: '/blog/posts/0002-learning-for-the-solution-architect-certificate'
      fullPath: '/blog/posts/0002-learning-for-the-solution-architect-certificate'
      preLoaderRoute: typeof BlogPosts0002LearningForTheSolutionArchitectCertificateImport
      parentRoute: typeof rootRoute
    }
    '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit': {
      id: '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit'
      path: '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit'
      fullPath: '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit'
      preLoaderRoute: typeof BlogPosts0003HowToGetTheMostOutOfAwsSummitImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ToDoListRoute,
  BlogIndexRoute,
  BlogPosts0001BuildingAwsCloudResumeChallengeRoute,
  BlogPosts0002LearningForTheSolutionArchitectCertificateRoute,
  BlogPosts0003HowToGetTheMostOutOfAwsSummitRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/to-do-list",
        "/blog/",
        "/blog/posts/0001-building-aws-cloud-resume-challenge",
        "/blog/posts/0002-learning-for-the-solution-architect-certificate",
        "/blog/posts/0003-how-to-get-the-most-out-of-aws-summit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/to-do-list": {
      "filePath": "to-do-list.tsx"
    },
    "/blog/": {
      "filePath": "blog/index.tsx"
    },
    "/blog/posts/0001-building-aws-cloud-resume-challenge": {
      "filePath": "blog/posts/0001-building-aws-cloud-resume-challenge.tsx"
    },
    "/blog/posts/0002-learning-for-the-solution-architect-certificate": {
      "filePath": "blog/posts/0002-learning-for-the-solution-architect-certificate.tsx"
    },
    "/blog/posts/0003-how-to-get-the-most-out-of-aws-summit": {
      "filePath": "blog/posts/0003-how-to-get-the-most-out-of-aws-summit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
