/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToDoListRouteImport } from './routes/to-do-list'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogPosts0006FollowingTheProcessRouteImport } from './routes/blog/posts/0006-following-the-process'
import { Route as BlogPosts0005AwsSolutionsArchitectDeveloperAssociateCertificatesRouteImport } from './routes/blog/posts/0005-aws-solutions-architect-developer-associate-certificates'
import { Route as BlogPosts0004AmazonQDeveloperGameBuilderChallengeRouteImport } from './routes/blog/posts/0004-amazon-q-developer-game-builder-challenge'
import { Route as BlogPosts0003HowToGetTheMostOutOfAwsSummitRouteImport } from './routes/blog/posts/0003-how-to-get-the-most-out-of-aws-summit'
import { Route as BlogPosts0002LearningForTheSolutionArchitectCertificateRouteImport } from './routes/blog/posts/0002-learning-for-the-solution-architect-certificate'
import { Route as BlogPosts0001BuildingAwsCloudResumeChallengeRouteImport } from './routes/blog/posts/0001-building-aws-cloud-resume-challenge'

const ToDoListRoute = ToDoListRouteImport.update({
  id: '/to-do-list',
  path: '/to-do-list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPosts0006FollowingTheProcessRoute =
  BlogPosts0006FollowingTheProcessRouteImport.update({
    id: '/blog/posts/0006-following-the-process',
    path: '/blog/posts/0006-following-the-process',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPosts0005AwsSolutionsArchitectDeveloperAssociateCertificatesRoute =
  BlogPosts0005AwsSolutionsArchitectDeveloperAssociateCertificatesRouteImport.update(
    {
      id: '/blog/posts/0005-aws-solutions-architect-developer-associate-certificates',
      path: '/blog/posts/0005-aws-solutions-architect-developer-associate-certificates',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const BlogPosts0004AmazonQDeveloperGameBuilderChallengeRoute =
  BlogPosts0004AmazonQDeveloperGameBuilderChallengeRouteImport.update({
    id: '/blog/posts/0004-amazon-q-developer-game-builder-challenge',
    path: '/blog/posts/0004-amazon-q-developer-game-builder-challenge',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPosts0003HowToGetTheMostOutOfAwsSummitRoute =
  BlogPosts0003HowToGetTheMostOutOfAwsSummitRouteImport.update({
    id: '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit',
    path: '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPosts0002LearningForTheSolutionArchitectCertificateRoute =
  BlogPosts0002LearningForTheSolutionArchitectCertificateRouteImport.update({
    id: '/blog/posts/0002-learning-for-the-solution-architect-certificate',
    path: '/blog/posts/0002-learning-for-the-solution-architect-certificate',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPosts0001BuildingAwsCloudResumeChallengeRoute =
  BlogPosts0001BuildingAwsCloudResumeChallengeRouteImport.update({
    id: '/blog/posts/0001-building-aws-cloud-resume-challenge',
    path: '/blog/posts/0001-building-aws-cloud-resume-challenge',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/to-do-list': typeof ToDoListRoute
  '/blog': typeof BlogIndexRoute
  '/blog/posts/0001-building-aws-cloud-resume-challenge': typeof BlogPosts0001BuildingAwsCloudResumeChallengeRoute
  '/blog/posts/0002-learning-for-the-solution-architect-certificate': typeof BlogPosts0002LearningForTheSolutionArchitectCertificateRoute
  '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit': typeof BlogPosts0003HowToGetTheMostOutOfAwsSummitRoute
  '/blog/posts/0004-amazon-q-developer-game-builder-challenge': typeof BlogPosts0004AmazonQDeveloperGameBuilderChallengeRoute
  '/blog/posts/0005-aws-solutions-architect-developer-associate-certificates': typeof BlogPosts0005AwsSolutionsArchitectDeveloperAssociateCertificatesRoute
  '/blog/posts/0006-following-the-process': typeof BlogPosts0006FollowingTheProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/to-do-list': typeof ToDoListRoute
  '/blog': typeof BlogIndexRoute
  '/blog/posts/0001-building-aws-cloud-resume-challenge': typeof BlogPosts0001BuildingAwsCloudResumeChallengeRoute
  '/blog/posts/0002-learning-for-the-solution-architect-certificate': typeof BlogPosts0002LearningForTheSolutionArchitectCertificateRoute
  '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit': typeof BlogPosts0003HowToGetTheMostOutOfAwsSummitRoute
  '/blog/posts/0004-amazon-q-developer-game-builder-challenge': typeof BlogPosts0004AmazonQDeveloperGameBuilderChallengeRoute
  '/blog/posts/0005-aws-solutions-architect-developer-associate-certificates': typeof BlogPosts0005AwsSolutionsArchitectDeveloperAssociateCertificatesRoute
  '/blog/posts/0006-following-the-process': typeof BlogPosts0006FollowingTheProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/to-do-list': typeof ToDoListRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/posts/0001-building-aws-cloud-resume-challenge': typeof BlogPosts0001BuildingAwsCloudResumeChallengeRoute
  '/blog/posts/0002-learning-for-the-solution-architect-certificate': typeof BlogPosts0002LearningForTheSolutionArchitectCertificateRoute
  '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit': typeof BlogPosts0003HowToGetTheMostOutOfAwsSummitRoute
  '/blog/posts/0004-amazon-q-developer-game-builder-challenge': typeof BlogPosts0004AmazonQDeveloperGameBuilderChallengeRoute
  '/blog/posts/0005-aws-solutions-architect-developer-associate-certificates': typeof BlogPosts0005AwsSolutionsArchitectDeveloperAssociateCertificatesRoute
  '/blog/posts/0006-following-the-process': typeof BlogPosts0006FollowingTheProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/to-do-list'
    | '/blog'
    | '/blog/posts/0001-building-aws-cloud-resume-challenge'
    | '/blog/posts/0002-learning-for-the-solution-architect-certificate'
    | '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit'
    | '/blog/posts/0004-amazon-q-developer-game-builder-challenge'
    | '/blog/posts/0005-aws-solutions-architect-developer-associate-certificates'
    | '/blog/posts/0006-following-the-process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/to-do-list'
    | '/blog'
    | '/blog/posts/0001-building-aws-cloud-resume-challenge'
    | '/blog/posts/0002-learning-for-the-solution-architect-certificate'
    | '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit'
    | '/blog/posts/0004-amazon-q-developer-game-builder-challenge'
    | '/blog/posts/0005-aws-solutions-architect-developer-associate-certificates'
    | '/blog/posts/0006-following-the-process'
  id:
    | '__root__'
    | '/'
    | '/to-do-list'
    | '/blog/'
    | '/blog/posts/0001-building-aws-cloud-resume-challenge'
    | '/blog/posts/0002-learning-for-the-solution-architect-certificate'
    | '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit'
    | '/blog/posts/0004-amazon-q-developer-game-builder-challenge'
    | '/blog/posts/0005-aws-solutions-architect-developer-associate-certificates'
    | '/blog/posts/0006-following-the-process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToDoListRoute: typeof ToDoListRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogPosts0001BuildingAwsCloudResumeChallengeRoute: typeof BlogPosts0001BuildingAwsCloudResumeChallengeRoute
  BlogPosts0002LearningForTheSolutionArchitectCertificateRoute: typeof BlogPosts0002LearningForTheSolutionArchitectCertificateRoute
  BlogPosts0003HowToGetTheMostOutOfAwsSummitRoute: typeof BlogPosts0003HowToGetTheMostOutOfAwsSummitRoute
  BlogPosts0004AmazonQDeveloperGameBuilderChallengeRoute: typeof BlogPosts0004AmazonQDeveloperGameBuilderChallengeRoute
  BlogPosts0005AwsSolutionsArchitectDeveloperAssociateCertificatesRoute: typeof BlogPosts0005AwsSolutionsArchitectDeveloperAssociateCertificatesRoute
  BlogPosts0006FollowingTheProcessRoute: typeof BlogPosts0006FollowingTheProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/to-do-list': {
      id: '/to-do-list'
      path: '/to-do-list'
      fullPath: '/to-do-list'
      preLoaderRoute: typeof ToDoListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/posts/0006-following-the-process': {
      id: '/blog/posts/0006-following-the-process'
      path: '/blog/posts/0006-following-the-process'
      fullPath: '/blog/posts/0006-following-the-process'
      preLoaderRoute: typeof BlogPosts0006FollowingTheProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/posts/0005-aws-solutions-architect-developer-associate-certificates': {
      id: '/blog/posts/0005-aws-solutions-architect-developer-associate-certificates'
      path: '/blog/posts/0005-aws-solutions-architect-developer-associate-certificates'
      fullPath: '/blog/posts/0005-aws-solutions-architect-developer-associate-certificates'
      preLoaderRoute: typeof BlogPosts0005AwsSolutionsArchitectDeveloperAssociateCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/posts/0004-amazon-q-developer-game-builder-challenge': {
      id: '/blog/posts/0004-amazon-q-developer-game-builder-challenge'
      path: '/blog/posts/0004-amazon-q-developer-game-builder-challenge'
      fullPath: '/blog/posts/0004-amazon-q-developer-game-builder-challenge'
      preLoaderRoute: typeof BlogPosts0004AmazonQDeveloperGameBuilderChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit': {
      id: '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit'
      path: '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit'
      fullPath: '/blog/posts/0003-how-to-get-the-most-out-of-aws-summit'
      preLoaderRoute: typeof BlogPosts0003HowToGetTheMostOutOfAwsSummitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/posts/0002-learning-for-the-solution-architect-certificate': {
      id: '/blog/posts/0002-learning-for-the-solution-architect-certificate'
      path: '/blog/posts/0002-learning-for-the-solution-architect-certificate'
      fullPath: '/blog/posts/0002-learning-for-the-solution-architect-certificate'
      preLoaderRoute: typeof BlogPosts0002LearningForTheSolutionArchitectCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/posts/0001-building-aws-cloud-resume-challenge': {
      id: '/blog/posts/0001-building-aws-cloud-resume-challenge'
      path: '/blog/posts/0001-building-aws-cloud-resume-challenge'
      fullPath: '/blog/posts/0001-building-aws-cloud-resume-challenge'
      preLoaderRoute: typeof BlogPosts0001BuildingAwsCloudResumeChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToDoListRoute: ToDoListRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogPosts0001BuildingAwsCloudResumeChallengeRoute:
    BlogPosts0001BuildingAwsCloudResumeChallengeRoute,
  BlogPosts0002LearningForTheSolutionArchitectCertificateRoute:
    BlogPosts0002LearningForTheSolutionArchitectCertificateRoute,
  BlogPosts0003HowToGetTheMostOutOfAwsSummitRoute:
    BlogPosts0003HowToGetTheMostOutOfAwsSummitRoute,
  BlogPosts0004AmazonQDeveloperGameBuilderChallengeRoute:
    BlogPosts0004AmazonQDeveloperGameBuilderChallengeRoute,
  BlogPosts0005AwsSolutionsArchitectDeveloperAssociateCertificatesRoute:
    BlogPosts0005AwsSolutionsArchitectDeveloperAssociateCertificatesRoute,
  BlogPosts0006FollowingTheProcessRoute: BlogPosts0006FollowingTheProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
